#include "constants.h"

int BACKGROUND_HEIGHT = 560;
int BACKGROUND_WIDTH = 1000;
int BASKET_SIZE = 150;
int BASKET_MOVE_STEP = 25;
int CHERRYBLOSSOM_SIZE = 80;
int CHERRYBLOSSOM_FALLING_SPEED = 25;
int CHERRYBLOSSOM_WIND_EFFECT = 20;
int CHERRYBLOSSOM_WIND_FREQUENCY = 15;
int CHERRYBLOSSOM_FALLING_INTERVAL = 1000;
int COLLISION_DETECTION_INTERVAL = 50;
int NUM_CHERRY_BLOSSOMS = 7;
