#ifndef CONSTANTS_H
#define CONSTANTS_H

extern int BACKGROUND_HEIGHT;
extern int BACKGROUND_WIDTH;
extern int BASKET_SIZE;
extern int BASKET_MOVE_STEP;
extern int CHERRYBLOSSOM_FALLING_SPEED;
extern int CHERRYBLOSSOM_SIZE;
extern int CHERRYBLOSSOM_WIND_EFFECT;
extern int CHERRYBLOSSOM_WIND_FREQUENCY;
extern int CHERRYBLOSSOM_FALLING_INTERVAL;
extern int COLLISION_DETECTION_INTERVAL;
extern int NUM_CHERRY_BLOSSOMS;

#endif // CONSTANTS_H
