#ifndef CONSTANTS_H
#define CONSTANTS_H

extern int BACKGROUND_HEIGHT;
extern int BACKGROUND_WIDTH;
extern int BASKET_SIZE;
extern int CHERRYBLOSSOM_SIZE;
extern int CHERRYBLOSSOM_WIND_EFFECT;
extern int CHERRYBLOSSOM_WIND_FREQUENCY;
extern int CHERRYBLOSSOM_FALLING_INTERVAL;
extern int COLLISION_DETECTION_INTERVAL;
extern int NUM_CHERRY_BLOSSOMS;
extern int DEFAULT_LIVES;
extern int SCORE_PER_COLLISION;

#endif // CONSTANTS_H
