
int BACKGROUND_HEIGHT = 560;
int BACKGROUND_WIDTH = 1000;
int BASKET_SIZE = 150;
int CHERRYBLOSSOM_SIZE = 80;
int CHERRYBLOSSOM_WIND_EFFECT = 20;
int CHERRYBLOSSOM_WIND_FREQUENCY = 15;
int CHERRYBLOSSOM_FALLING_INTERVAL = 1000;
int COLLISION_DETECTION_INTERVAL = 50;
int NUM_CHERRY_BLOSSOMS = 7;
int DEFAULT_LIVES = 9;
int SCORE_PER_COLLISION = 5;
int CHERRYBLOSSOM_SPEEDUP_THRESHOLD = 5;
float CHERRYBLOSSOM_SPEEDUP_FACTOR = 1.5;
